# fly.toml file generated for productos on 2023-04-04T14:12:24-05:00

app = "productos"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bog"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
