default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  pool: <%= ENV["POSTGRESQL_POOL"] %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] %>
  port: <%= ENV["POSTGRESQL_PORT"] %>

development:
  <<: *default
  database: productos_development

test:
  <<: *default
  database: productos_test

production:
  <<: *default
  database: productos_production

